### ISSUE TITLE
Clang-tidy/clang-format being installed clashed with system binaries

### ISSUE THREAD

**Issue by burgholzer** [cpp-linter/cpp-linter-action#103]
Hey :wave:

First of all, thanks for this project and all the work you put in over the last couple of weeks to improve it.

We recently adopted the action for our project https://github.com/cda-tum/qcec. 
Since we initially had problems with `v1` and the compilation database, we switched to using the Python package instead.

After the `v2` release, I tried to switch to the action again (https://github.com/cda-tum/qcec/pull/132), which seemed to work great. Unfortunately (as I later found out in https://github.com/cda-tum/qcec/pull/136), under the hood, this silently failed due a segmentation fault in `clang-tidy-14`.
In that PR, I tried all kinds of twists and turns to make things work, but neither downgrading the GitHub runner image nor the clang-tidy version produced proper results.
In the end, I switched back to using `pipx` and the core `cpp-linter` package, which works effortlessly for now 🎉.

My best guess after a long night of debugging why all my efforts have been failing in [that PR](https://github.com/cda-tum/qcec/pull/136) is that GitHub runners come with certain versions of the LLVM toolchain by default (typically the three latest versions). For `Ubuntu-22.04` that's `clang/clang-tidy/clang-format` versions `12`, `13`, and `14`.
When running the `cpp-linter-action`, it tries to automatically download and install the respective clang-format and clang-tidy versions using `clang-tools`. It's only a guess, but somehow this messes up the subsequent cpp-linter run (see, e.g., https://github.com/cda-tum/qcec/runs/8217659640?check_suite_focus=true#step:4:114 where it can't find the `<stddef.h>` system header all of a sudden).

One possible fix could be to check whether the version requested from the `cpp-linter-action` is available on the current system. If yes, then use the existing binaries. If no, proceed as before.
This also allows to use this action under `Ubuntu-22.04` with `clang-tidy-14` (it would probably also not hurt to document the segfault issue of the `clang-tools` binary for `clang-tidy-14` under Linux here).

Let me know, what you think. It would be great to switch back to using the GitHub action after all (let alone that it contributes to the `Used by ...` statistic 😃 )

**Comment by 2bndy5** [comment]
> And I see almost no reason for that linter workflow to not run under Linux.

We have had multiple users ask about how to the action in a Windows-only workflow. It's not always the case to have a separate workflow just for linting. In C++, it's very common to have a linter check before compiling in the same workflow because the database is generated when the CMake build env is configured.

> However, I can't believe that we are the only ones facing problems with properly setting up this action.

We just released v2 less than a week ago. It is likely that others have pinned the action to a specific commit SHA or `@v1`

I'm thankful for your feedback, and I do intend to look closer at the static binaries that we are using.

**Comment by burgholzer** [comment]
> > And I see almost no reason for that linter workflow to not run under Linux.
> 
> We have had multiple users ask about how to the action in a Windows-only workflow. It's not always the case to have a separate workflow just for linting. In C++, it's very common to have a linter check before compiling in the same workflow because the database is generated when the CMake build env is configured.
> 
True true. Didn't think that through fully.

> > However, I can't believe that we are the only ones facing problems with properly setting up this action.
> 
> We just released v2 less than a week ago. It is likely that others have pinned the action to a specific commit SHA or `@v1`
> 
> I'm thankful for your feedback, and I do intend to look closer at the static binaries that we are using.

Thanks again for all your efforts and for responding so quickly!
If there is anything, where we could help, let us know.
At the moment, we have a working solution using the core package so it's all good.

Just to summarize: we didn't manage to get the GitHub action running properly in any of the following configurations for our project:
| GitHub Runner | cpp-linter `version` | compilation database compiler | result | run |
| --- | --- | --- | --- | --- |
| Ubuntu-22.04 | 14 | clang-14 | segfault | https://github.com/cda-tum/qcec/runs/8217114823?check_suite_focus=true
| Ubuntu-22.04 | 13 | clang-14 | stdlib header not found | https://github.com/cda-tum/qcec/runs/8217659640?check_suite_focus=true
| Ubuntu-22.04 | 13 | clang-13 | stdlib header not found | https://github.com/cda-tum/qcec/runs/8217934578?check_suite_focus=true
| Ubuntu-22.04 | 12 | clang-12 | stdlib header not found | https://github.com/cda-tum/qcec/runs/8218038348?check_suite_focus=true
| Ubuntu-20.04 | 14 | clang-12 | segfault | https://github.com/cda-tum/qcec/runs/8218075258?check_suite_focus=true
| macOS-latest | 14 | clang-13 | No such file or directory: 'clang-tidy-14' | https://github.com/cda-tum/qcec/runs/8218221741?check_suite_focus=true

One last guess at the potential source of the problem:
Could it be that the compiler that is listed in the compilation database is (for whatever reason) not compatible with the `clang-tidy` installed from `clang-tools`?

**Comment by 2bndy5** [comment]
> not compatible with the clang-tidy installed from clang-tools?

This is what I intend to find out. We haven't tested v14 due to the seg fault but. It may be that statically compiling against a certain dist of libc++ has unintended consequences.

**Comment by 2bndy5** [comment]
@burgholzer We just published a new version of clang-tools-pip pkg that should use the system's dynamically linked binaries when the version exactly matches the user input; version 12 will only use the system's v12.0.0 binaries if they are installed, and version 12.0.1 will only use v12.0.1 if installed... Hopefully, that should resolve most problems with clang-tidy not finding std libs.

**Comment by burgholzer** [comment]
> @burgholzer We just published a new version of clang-tools-pip pkg that should use the system's dynamically linked binaries when the version exactly matches the user input; version 12 will only use the system's v12.0.0 binaries if they are installed, and version 12.0.1 will only use v12.0.1 if installed... Hopefully, that should resolve most problems with clang-tidy not finding std libs.

Thanks! I'll try that out over the next couple of days and get back to you 👍🏼

**Comment by 2bndy5** [comment]
That would much appreciated. User feedback is a great way to contribute!

**Comment by 2bndy5** [comment]
>This error is reported by clang-tidy. Currently, we do not support disabling clang-tidy to run only clang-format.

Actually, this can be done by setting `tidy-checks` to `-*`.

---
To be clear, clang-tidy is having trouble with analyzing the includes in stdio.h
> /usr/include/stdio.h:33:10: error: 'stddef.h' file not found [clang-diagnostic-error]
> #include <stddef.h>

This is what made me think there was a problem related to the C++ distribution that is installed. Although I'm not entirely clear where clang-tidy is looking for the stddef.h header. Typically, the AST generated by clang uses absolute paths, so it would be nice to get an AST tree dump from a machine that can reproduce this locally.

**Comment by 2bndy5** [comment]
I found [this stackoverflow Q/A](https://stackoverflow.com/questions/20587228/clang-error-stddef-file-not-found) interesting.

**Comment by 2bndy5** [comment]
> Download clang-tidy with `clang-tools`. clang-tools still download clang-tidy binary even though native binary exists.

This might have something to do with comparing a tuple of strings instead of a tuple of integers. See https://github.com/cpp-linter/clang-tools-pip/blob/ce41d4f571abeffc4bfa94b65682804f2cda1613/clang_tools/install.py#L59

We should have verified the CI more thoroughly... We missed this in the CI logs ([evidently](https://github.com/cpp-linter/clang-tools-pip/actions/runs/3194440363/jobs/5214018472#step:5:12)).
