### ISSUE TITLE
`set-output` command is deprecated and will be disabled soon

### ISSUE THREAD

**Issue by shenxianpeng** [cpp-linter/cpp-linter-action#108]
```bash
[cpp-linter (11)](https://github.com/cpp-linter/test-cpp-linter-action/actions/runs/3247052956/jobs/5326536419#step:11:145)
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

```bash
[cpp-linter (9)](https://github.com/cpp-linter/test-cpp-linter-action/actions/runs/3247052956/jobs/5326536298)
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/checkout
```

 see https://github.com/cpp-linter/test-cpp-linter-action/actions/runs/3247052956

**Comment by 2bndy5** [comment]
[Using an env var](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable) seems easy to migrate to, but both v1 and v2 have to be adjusted... Unless you want v1 to become [more] broken.

**Comment by 2bndy5** [comment]
The  second warning isn't a problem with the cpp-linter-action. It just means that we have to update the version of `actions/checkout` used in the workflow file. I recently had to solve this with another repo.

**Comment by 2bndy5** [comment]
looks like v1 is already set to use the latest cpp-linter release:
https://github.com/cpp-linter/cpp-linter-action/blob/17526ee926252f8882bbb9afc07c1c29456036e8/setup.py#L13

I'm ok with that, but feel free to pin it to a specific version if you want.
