### ISSUE TITLE
Needs option to delete old PR comments

### ISSUE THREAD

**Issue by turol** [cpp-linter/cpp-linter-action#119]
From https://github.com/chocolate-doom/chocolate-doom/pull/1537
I got some (correct) complains about file `src/hexen/p_action.h `
I force-pushed the branch to correct them. The old comments were not deleted. This makes it hard to check if all the things have been fixed.

**Comment by 2bndy5** [comment]
I have to checkwith the github REST API docs (optimistic it will help). My first guess is that the force push, which basically resets the branch's history, may be hiding the PR's full history, thus acting like a PR just opened.

**Comment by 2bndy5** [comment]
Just to be clear, there is a difference between `file-annotations` and `thread-comments`.
1. `thread-comments` look like user comments that are only displayed in the PR's thread (or after the diff for a commit on push events). ![image](https://user-images.githubusercontent.com/14963867/204106802-ae9c240a-2351-478c-bc40-ce9ca417453a.png) These are automatically deleted every time cpp-linter-action runs. 
2. `file-annotations` are comments posted within the diff for an event.  ![image](https://user-images.githubusercontent.com/14963867/204107159-58b27c69-439c-403a-b55c-9241543d6d3b.png)
These cannot be deleted as they are specific to the commit that triggered the CI event. This is not our choice, it is a limitation of the [workflow log commands](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#about-workflow-commands) that we use to post the annotations. Existing annotations cannot be fetched without recursively searching the parent commits (which would result in a catastrophic failure on forced pushed commits), and I'm still not sure its even possible to get a list of previous annotations via GitHub's REST API.

    I had initially planned to use GitHub Checks API to post file-annotations, but I ended up going with workflow log commands because it didn't require a server constantly running a GitHub app (which costs 💰 AFAIK).

Therefore, we cannot offer an option to delete `file-annotations`. And `thread-comments` are automatically deleted on every run of cpp-linter-action. I'm closing this... Feel free to comment if I somehow misinterpreted the request.
