### ISSUE TITLE
Cannot get comments displayed on github/pull page

### ISSUE THREAD

**Issue by malaterre** [cpp-linter/cpp-linter-action#135]
For some reason I do not see any clang-tidy bot comment on my github/pull page:

* https://github.com/malaterre/libdicm/pull/48

Using the following setup:

* https://github.com/malaterre/libdicm/blob/9c109fc73cf75473374f51f6afd6d2043a89458e/.github/workflows/clang-tidy-review.yml

Am I missing something from the documentation ? Thanks much

**Comment by 2bndy5** [comment]
The `thread-comments` option is disabled by default. You need to add
```yml
thread-comments: true
```
to your config.

**Comment by 2bndy5** [comment]
Currently, there won't be any comment if all checks pass. We will be changing that though (see cpp-linter/cpp-linter#24)

**Comment by 2bndy5** [comment]
I suppose we could try using it implicitly (haven't considered it). I personally prefer users know when write/read privileges are being used by a third party.
