### ISSUE TITLE
Iinter keep giving 1 error & notice

### ISSUE THREAD

**Issue by taehwan642** [cpp-linter/cpp-linter-action#143]
https://github.com/taehwan642/math/actions/runs/4698040597/jobs/8329832480
this is my current linter job, and it keeps giving fail..
I thought it was because of the compilation database missing, but it wasn't.
**Is there any problem with my github action?**
And it keeps giving me some notice about `File header/Vector2.hpp does not conform to Custom style guidelines. (lines 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 15, 16, 17, 18, 19, 20, 22, 23, 24, 26, 28)`
**so is there any reason linter keep gives me notice?**
thank you.

**Comment by 2bndy5** [comment]
If you look at [the summary of that run](https://github.com/taehwan642/math/actions/runs/4698040597), You'll see the full Notification which should be something like "Run clang-format on \<file>".

It basically means that the files' format doesn't match the output of
```bash
clang-format-12 -style=Google path/to/filename.x
```

Please make sure the version you use locally is the [`version`](https://github.com/cpp-linter/cpp-linter-action#version) you use by the action as there are differences between major versions of clang-format.

**Comment by taehwan642** [comment]
Thank you for answering!
So the 1 error means that I didn't matched the format?
To fix, I need to match the file's format to Google is that right?
Is there any way to see the output of `clang-format-12 -style=Google path/to/filename.x`?

**Comment by taehwan642** [comment]
I changed the repository - action access to read/write to add comment.

**Comment by 2bndy5** [comment]
If you run clang-format on the file, then it should then be in the correct/expected format. Do this by running
```bash
clang-format-12 -style=Google path/to/filename.x
```
You could try the `-dry-run` arg as well, but this question has really turned into a "how to use clang-format?" I would suggest you explore that first before considering this action in your CI.

**Comment by taehwan642** [comment]
Oh I formatted the code, and it worked! thanks!
