### ISSUE TITLE
Update README about new step-summary and revised thread comments

### ISSUE THREAD

**Issue by shenxianpeng** [cpp-linter/cpp-linter-action#151]
We need to update README.md 
1. Add optional input about the new feature "step-summary" (maybe need to add a screenshot) 
2. Update existing screenshots about thread comments (e.g https://github.com/cpp-linter/cpp-linter-action/commit/1045e02632d0fce3c5ea18d9380969ee7338289b)

**Comment by 2bndy5** [comment]
I added a link to the github docs (in #152) alluding to the misconception about "step summary" vs "job summary". Maybe the new screenshot could also have a caption that would help clear any remaining confusion.
