### ISSUE TITLE
Update thread comment once format checks are successful.

### ISSUE THREAD

**Issue by pshriwise** [cpp-linter/cpp-linter-action#154]
Thank you for providing this really handy action! When trying it out, I found that the thread comment would update if new/different problems with the formatting appear. It would be nice if the action also updated the comment when the format checks are successful to avoid confusion about outstanding formatting issues in the PR content.

Here is the set of options I'm using w/ `v2`:

```
          style: file
          files-changed-only: true
          tidy-checks: '-*'
          version: '15'
          thread-comments: true
          file-annotations: false
          step-summary: true
          extensions: 'cpp,h'
```

**Comment by 2bndy5** [comment]
It should auto-update the thread comment if the event trigger is a PR (ie PR sync event). However, if you trigger cpp-linter with a push event, then the comment might not auto-update in the PR thread.

**Comment by pshriwise** [comment]
In our workflows (and maybe most), the PR is going to be updated by a push to the feature branch. Is there a technical barrier to ensuring that the thread comment is updated for push events?

**Comment by pshriwise** [comment]
Ah I see. Thanks for explaining. I think the `file-annotations` will be sufficient for our needs and do seem to update as expected. Thanks for your time!
