### ISSUE TITLE
How to specify "Build path" (`-p`) for .clang-tidy?

### ISSUE THREAD

**Issue by satelllte** [cpp-linter/cpp-linter-action#157]
Hi 👋 
First of all, thanks for this amazing GitHub Action!

Question: 
How to pass `-p build` CLI option into `clang-tidy` CLI?

**Comment by 2bndy5** [comment]
Its the input option named [`database`](https://github.com/cpp-linter/cpp-linter-action#database).

**Comment by satelllte** [comment]
Sorry, just figured it out that there's `database` option:

```yml
with:
  database: 'build'
```

Thanks for such quick answer !

Closing this issue ...
