### ISSUE TITLE
Warning: 2 File(s) not formatted (should be 1)

### ISSUE THREAD

**Issue by Bromvlieg** [cpp-linter/cpp-linter-action#161]
Hey there,

I noticed it gives a warning about `not formatted`. But what does that mean?
Also the warning says 2 files, but the list only contains one?

![image](https://github.com/cpp-linter/cpp-linter-action/assets/1164341/7902efb0-8f60-459c-b2a7-5b781ab45c9c)

**Comment by 2bndy5** [comment]
It's definitely a bug. Looking at the CI logs, I see that it should say only 1 file needs formatting.

**Comment by 2bndy5** [comment]
> But what does that mean?

It means you should run clang-format on the file listed. If you're telling cpp-linter-action to only analyze `lines-changed-only`, then you only need to run clang-format on the changed lines.

**Comment by Bromvlieg** [comment]
I've updated the title of the issue to reflect the bug better, I'll leave it open for when a commit is made to alter the behavior.

I'm still confused about what's going on with the `packet.hpp` file but that's outside of `cpp-linter-action`'s scope so I'll keep that inside the pull request I did at https://github.com/edunad/rawrbox/pull/109

Thank you for your help ❤!
