### ISSUE TITLE
Seperate output for `clang-format` and `clang-tidy`

### ISSUE THREAD

**Issue by makslevental** [cpp-linter/cpp-linter-action#168]
Would you take a PR that separates `steps.linter.outputs.checks-failed` into `steps.linter.outputs.clang-format-checks-failed` and `steps.linter.outputs.clang-tidy-checks-failed`? I would like to block on formatting but only post the comments from `clang-tidy`.

**Comment by 2bndy5** [comment]
I think adding more specific outputs is a good idea. Hint: the tally of `checks-failed` is counted in [`make_annotations()`](https://github.com/cpp-linter/cpp-linter/blob/99aa4698805d44d48ffadf67161f562af022d417/cpp_linter/run.py#L564) (despite the value of `file-annotations` input). IIRC, the output value is set in [`set_exit_code()`](https://github.com/cpp-linter/cpp-linter/blob/99aa4698805d44d48ffadf67161f562af022d417/cpp_linter/run.py#L55).

**Comment by 2bndy5** [comment]
> you know i was wondering if an empty string disabled clang-format. Thanks!

No problem. It is [noted in the README](https://github.com/cpp-linter/cpp-linter-action#style). See also the [`tidy-checks` explanation in README](https://github.com/cpp-linter/cpp-linter-action#tidy-checks).

**Comment by makslevental** [comment]
Reading comprehension ++ (also I've been up for like 40 hours lol). Thanks again.
