### ISSUE TITLE
Python `error: externally-managed-environment` during installation

### ISSUE THREAD

**Issue by zjeffer** [cpp-linter/cpp-linter-action#171]
I'm setting up a clang-tidy action for the Waybar repo: https://github.com/zjeffer/Waybar/blob/90208f8c17b815e3a50265e679a184354f5dcd9b/.github/workflows/clang-tidy.yml

I'm using [Waybar's debian image](https://github.com/Alexays/Waybar/blob/master/Dockerfiles/debian) as a base because I need to configure with meson before running clang-tidy, to generate compile_commands.json. I noticed that with this image, I had to install both `sudo` and `python3-pip` to fix errors during the installation.

After this, there's one error left when it runs `python3 -m pip install -r "$GITHUB_ACTION_PATH/requirements.txt"` in this repo's action.yaml:

```
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
Error: Process completed with exit code 1.
```

I was wondering if this error could be fixed by using a venv for all OSes, not just macOS like what you're doing here: https://github.com/cpp-linter/cpp-linter-action/blob/v2/action.yml#L130-L134. Would that fix this error?

**Comment by zjeffer** [comment]
> If the --user option is feasible fix then we could accept that change.

Great, I'll test this and make a PR.

> The new error you encountered seems similar to https://github.com/cpp-linter/cpp-linter/issues/30 which details known problems with the relative paths that Meson puts in the compilation database file; relative paths used in the database are not friendly with clang-tidy.

I think it's also because I need to build the entire project, not just configure it with Meson, to generate those xdg files. I'll test this too.

**Comment by zjeffer** [comment]
Adding --user to `python3 -m pip install` didn't fix it: https://github.com/zjeffer/Waybar/actions/runs/7129953996/job/19415221902

**Comment by 2bndy5** [comment]
It would be nice to see the output of `echo "hello, $USER"` when used within this docker.
- If it prints "hello, runner", then a venv would certainly be in order.
- If it prints "hello, root", then the docker needs to be configured with a non-root user.

Our previous attempt to use a python venv didn't work well because we were trying to avoid altering the PATH variable in the runner's context. It may be time to revisit that idea.

**Comment by 2bndy5** [comment]
Looking more into [PEP668](https://peps.python.org/pep-0668/#abstract):

> This PEP proposes a mechanism for a Python installation to communicate to tools like pip that its global package installation context is managed by some means external to Python, such as an OS package manager. It specifies that Python-specific package management tools should neither install nor remove packages into the interpreter’s global context, by default, and should instead guide the end user towards using a virtual environment.

Meaning, _**ALL**_ `pip` usage should now be used within a venv. I see why they (pip as of v23.0) chose to add this notification, but I think it should've been a warning level notification, not an error (at least for a limited probation period).

This also means the `ubuntu-latest` runner image is still using an older pip version (v22.0.2 as of this writing) which is why the error hasn't surfaced yet (in our test or as user-feedback).

**Comment by 2bndy5** [comment]
@zjeffer I just pushed an attempt to fix this with a py venv. Please try our use-py-venv branch:
```yml
    - uses: cpp-linter/cpp-linter-action@use-py-venv
```
and let me know if that works better with the docker image (please include link to workflow run).

**Comment by 2bndy5** [comment]
I did do an experimental port of our python code to dart which would have much less problems as far as package install goes. We ended up going against that in deployment because not many involved in this project are familiar with dart.

Locally, I also have the beginnings of a rust port of our python code, but it far from finished.

**Comment by zjeffer** [comment]
What if you don't install Python in the action, but assume/require the host image to already have it installed? Then you don't have to pass the exe path through an output variable.

You'll then be able to create a venv with one command, regardless of the OS:
`python3 -m venv $env:GITHUB_ACTION_PATH/venv`
`python3 -m pip install -r "$env:GITHUB_ACTION_PATH/requirements.txt"`

And activate it based on the OS:
```sh
if windows; then
    # i don't know how this actually works, but I assume there is a way in windows to run a script from sh?
    . "$env:GITHUB_ACTION_PATH/venv/scripts/Activate.ps1" 
else:
    . "$env:GITHUB_ACTION_PATH/venv/bin/activate"
fi
```

**Comment by 2bndy5** [comment]
> I might be able to remedy this by ensuring pwsh is installed in the "Install Linux deps" step.

Powershell requires the .NET core runtime as a dependency. This idea may be non-trivial.

**Comment by zjeffer** [comment]
I don't understand, don't you already assume it is installed? In the main branch, you're using python here: https://github.com/cpp-linter/cpp-linter-action/blob/main/action.yml#L134.

You're already using a venv if the OS is macOS, so my proposal is to use a venv for all OSes (like the PEP you posted recommends). 

Something like this:

https://github.com/cpp-linter/cpp-linter-action/compare/main...zjeffer:cpp-linter-action:main

(not tested on Windows but this is basically what I did in order to make it run in the Waybar repo, using a debian base image)

**Comment by 2bndy5** [comment]
Please note that this action will also break if a fedora or non-debian based linux docker image is used. What I'm trying to say is that we can't be expected to support _all_ possible CI configs because github actions is so flexible. What we have currently took a lot of time and learning to establish (with no funding).

**Comment by 2bndy5** [comment]
An alternative approach would be to use our [cpp-linter python package](https://github.com/cpp-linter/cpp-linter) by itself. But without the nuanced setup process that this repo performs, users would still have to ensure that clang-format and clang-tidy are installed before running our [cpp-linter CLI](https://cpp-linter.github.io/cpp-linter/cli_args.html). See also [`pipx`](https://github.com/pypa/pipx) as it was designed for that kind of scenario.

**Comment by zjeffer** [comment]
> Again the only problem with that patch is that it will not run on Windows because the bash shell removes the windows path delimiters. For example:
$GITHUB_ACTION_PATH resolves to (on Windows) D:\a\_actions\cpp-linter\cpp-linter-action, but in bash this path becomes D:a_actionscpp-lintercpp-linter-action. Remember that the path to the compilation database suffers the same problem in bash on windows runners.

I tested this on [this branch](https://github.com/cpp-linter/cpp-linter-action/compare/main...zjeffer:cpp-linter-action:feat/zjeffer/test) and I can't reproduce the issue with the GITHUB_ACTION_PATH resolving to that path without slashes. Am I testing this wrong?

Here's the workflow: https://github.com/zjeffer/cpp-linter-action/actions/runs/7143659190

> I don't see a robust way around this problem since we can't be expected to know what is or isn't installed in docker images that are not maintained by github actions. We may require users install pwsh in workflows that use non-default docker images in github actions runners (same would apply to self-hosted runners).

I fully understand where you're coming from, but I just really dislike PowerShell ;)

---

> @zjeffer It isn't pretty, but I used steps.if field to trigger certain shells native to the detected OS. It involves having 2 separate (& nearly identical) scripts for unix or windows. Please try the use-py-venv branch again.

Works: https://github.com/zjeffer/Waybar/actions/runs/7143645392/job/19455586940

**Comment by 2bndy5** [comment]
> I tested this on [this branch](https://github.com/cpp-linter/cpp-linter-action/compare/main...zjeffer:cpp-linter-action:feat/zjeffer/test) and I can't reproduce the issue with the GITHUB_ACTION_PATH resolving to that path without slashes. Am I testing this wrong?

That seems like you did everything right. We haven't had success last time we tried that though (probably about a year ago now). I'm still curious to see how the path to the database is shown in bash on Windows (originally reported in #155).

> Works: https://github.com/zjeffer/Waybar/actions/runs/7143645392/job/19455586940

Good to hear! I'm not a fan of maintaining duplicate scripts. Thankfully the scripts used here are very basic/simple. I'll keep playing around with this as I'd like to be sure that #155 is resolved (absolute paths should be preferred on any OS).

>I fully understand where you're coming from, but I just really dislike PowerShell ;)

This may sound like a broken record, but I can't assume that bash is available on all Windows runners. I can assume that pwsh is because it is shipped with the OS (meant to be a replacement for the old DOS CLI). Just to be clear, bash can be installed on Windows and usually is when git is installed on windows. Luckily, Github doesn't use SVN or Mercurial, but that doesn't guarantee a self hosted Windows runner will have git (& bash.exe) installed and added to PATH. Likewise, we already know that it isn't safe to assume pwsh isn't guaranteed to be installed on all Unix OS.

PS - I'm not a huge fan of the powershell conventions, ie. casing, very long winded API names that might be hyphenated (seems like it was developed by Visual Basic experts), and no way to escape the LF for multi-line statements. But I am a fan of whatever works 😎.

**Comment by zjeffer** [comment]
> That seems like you did everything right. We haven't had success last time we tried that though (probably about a year ago now). I'm still curious to see how the path to the database is shown in bash on Windows (originally reported in https://github.com/cpp-linter/cpp-linter-action/issues/155).

Strangely, that bug still occurs. I'll try to find a fix.

> This may sound like a broken record, but I can't assume that bash is available on all Windows runners. I can assume that pwsh is because it is shipped with the OS (meant to be a replacement for the old DOS CLI). Just to be clear, bash can be installed on Windows and usually is when git is installed on windows. Luckily, Github doesn't use SVN or Mercurial, but that doesn't guarantee a self hosted Windows runner will have git (& bash.exe) installed and added to PATH. Likewise, we already know that it isn't safe to assume pwsh isn't guaranteed to be installed on all Unix OS.

I think we have a couple of choices:
1. Use steps.if to choose between shells based on the runner
2. Assume bash is required to be installed on Windows runners and use bash everywhere
3. Assume pwsh is required to be installed on Linux runners and use pwsh everywhere

1 works but is harder to maintain and not as pretty.
Personally, I would prefer 2. The problem is that #155 still occurs.
I don't think 3 is a good idea because I believe there are a lot more people with Linux runners than Windows runners, and I can imagine most people install bash on Windows runners anyway, while very few people install pwsh on Linux runners.

**Comment by 2bndy5** [comment]
I've been coding for nearly ten years now, and I've found it is best to avoid writing code with assumptions in mind. Thus, options 2 and 3 aren't very appealing to me. I can cope with a little duplication (the scripts here aren't very complex).

Unfortunately, as we've seen here, it is hard to know when you are working with an assumption in mind, like the fact that all users will only be using github's runner images and not some custom docker image.

----
I tried reproducing #155 with the duplicate script approach. The path delimiter passed to the `database` input option needs to use delimiters appropriate to the OS used. I think I can fix that problem in our python code's `run_clang_tidy()`, but it seems that clang-tidy is still failing to find the database when given a path it can understand and traverse. See my experiment results in [this workflow run](https://github.com/cpp-linter/test-cpp-linter-action/actions/runs/7145155284/job/19460247779).

**Comment by zjeffer** [comment]
I think I fixed the database path in the action.yml file itself: https://github.com/cpp-linter/cpp-linter-action/compare/main...zjeffer:cpp-linter-action:feat/zjeffer/test#diff-1243c5424efaaa19bd8e813c5e6f6da46316e63761421b3e5f5c8ced9a36e6b6R150
If we simply replace backslashes with forward slashes, it works: https://github.com/zjeffer/cpp-linter-action/actions/runs/7151821064/job/19476496676

**Comment by 2bndy5** [comment]
Technically you have a path that uses both `/` and `\` because the `${{github.workspace}}` uses Windows path delimiters. I tried the same but got bad results (see [run log here](https://github.com/cpp-linter/test-cpp-linter-action/actions/runs/7145083498/job/19460029936)). However, I didn't terminate the path with a delimiter in my attempts. I wonder if that is important or crucial for clang-tidy's internal path handing.

**Comment by 2bndy5** [comment]
> However, I didn't terminate the path with a delimiter in my attempts. I wonder if that is important or crucial for clang-tidy's internal path handing.

Nope. Still got `Could not auto-detect compilation database from directory "D:\a\test-cpp-linter-action\test-cpp-linter-action/build/"` in clang-tidy output.

@zjeffer The other difference between our attempts at reproducing #155 is that I'm using a CMake generated compilation database (`compile_commands.json`). Your attempt is using a static global compilation database (`compile_flags.txt`). It is much more common to use a generated database as the build system tends to be manipulated often during development.

**Comment by zjeffer** [comment]
> Technically you have a path that uses both / and \ because the ${{github.workspace}} uses Windows path delimiters. I tried the same but got bad results (see [run log here](https://github.com/cpp-linter/test-cpp-linter-action/actions/runs/7145083498/job/19460029936)). However, I didn't terminate the path with a delimiter in my attempts. I wonder if that is important or crucial for clang-tidy's internal path handing.

Well no, in my case I replace the backslashes with forward slashes right before passing it to cpp-linter: 

https://github.com/zjeffer/cpp-linter-action/actions/runs/7151821064/job/19476496676#step:4:116

> database_path: D:\a\cpp-linter-action\cpp-linter-action/demo/
> database_path after replacing: D:/a/cpp-linter-action/cpp-linter-action/demo/

Here's what I do in action.yml: https://github.com/zjeffer/cpp-linter-action/blob/feat/zjeffer/test/action.yml#L150

> database_path=$(printf "%s" "${{ inputs.database }}" | sed 's:\\:/:g')

(echo removed the backslashes so I had to use printf)

**Comment by 2bndy5** [comment]
>  in my case I replace the backslashes with forward slashes right before passing it to cpp-linter

Hmm. So you basically workaround the fact that bash can't handle windows path delimiter (outside of regex patterns) by adding extra logic to the bash script. I prefer all our path manipulation happen in our python codebase. You're also relying on `printf` being available/installed. I would call that an assumption, but it _might_ be safe to assume all bash-enabled environments have the `printf` command available.

**Comment by zjeffer** [comment]
> Hmm. So you basically workaround the fact that bash can't handle windows path delimiter (outside of regex patterns) by adding extra logic to the bash script. I prefer all our path manipulation happen in our python codebase.

Ah, I understand now. I was under the impression the path to the database that was being passed to cpp-linter had no slashes. If it gets passed correctly to python, then it indeed makes sense to let Python replace the backslashes with forward slashes. Have you tried that yet?

**Comment by 2bndy5** [comment]
> If it gets passed correctly to python, then it indeed makes sense to let Python replace the backslashes with forward slashes. Have you tried that yet?

It doesn't get correctly passed to python. At least that's how #155 was reported.

In python, we just normalize a relative path to DB into an absolute path, and use an absolute path to DB is used as is. See [code here](https://github.com/cpp-linter/cpp-linter/blob/a2875ac00e6f1dc3eb4ac19712c7a241b5a76e83/cpp_linter/run.py#L319-L323)
