### ISSUE TITLE
Preparing for v2.9.0 PR review feature release

### ISSUE THREAD

**Issue by shenxianpeng** [cpp-linter/cpp-linter-action#182]
To release `v2.9.0` PR review and other improvements need to complete the following tasks

- [x] Release [cpp-linter/cpp-linter](https://github.com/cpp-linter/cpp-linter/releases) `v1.7.0`
- [x] Update README.md file. refer to https://github.com/cpp-linter/cpp-linter-action/issues/182#issuecomment-1893261603
- [x] Add a screenshot of the new feature [PR review](https://github.com/cpp-linter/cpp-linter/issues/50) to show how it works
- [x] Include #187

**Comment by 2bndy5** [comment]
<details><summary>from <a href="https://github.com/cpp-linter/test-cpp-linter-action/pull/26">test PR 1</a></summary>

![image](https://github.com/cpp-linter/cpp-linter-action/assets/14963867/235c6cf4-b933-4bbe-b6e4-c16e8e71c8a1)
![image](https://github.com/cpp-linter/cpp-linter-action/assets/14963867/31a5f359-87f3-4225-acc6-404f13212f01)

</details>

<details><summary>from <a href="https://github.com/cpp-linter/test-cpp-linter-action/pull/27">test PR 2</a></summary>

![image](https://github.com/cpp-linter/cpp-linter-action/assets/14963867/14e0d73e-9fcc-4b20-b5a0-c6faf637215b)

</details>

---
There are other caveats to note about this feature
1. The "GitHub Actions" bot may need to be allowed to approve PRs. This can be done in the repo settings (or in org settings if applicable). By default, the bot cannot approve PR changes, only request more changes. This will show as a logged warning if the given token isn't configured with the proper permissions.
2. The feature is auto-disabled for 
   - closed PRs
   - PRs marked as "draft"
   - push events
3. Clang-tidy and clang-format suggestions are shown in 1 PR review. 
   - Users are encouraged to choose either `tidy-review` or `format-review`. Enabling both will likely show duplicate or similar suggestions. Remember, clang-format can be configured to use the same `style` that clang-format accepts. There is no current implementation to combine suggestions from both tools (clang-format kind of does that anyway).
   - Each generated review is specific to the commit that triggered the CI.
   - Outdated reviews are dismissed but not marked as resolved. Also, the outdated review's summary comment is not automatically hidden. To reduce PR thread noise, users interaction is required. GitHub REST API does not provide a way to hide comments or mark review suggestions as resolved.
4. If any suggestions did not fit within the PR diff, then the review's summary comment will indicate how many suggestions were left out. The full patch of suggestions is always included as a collapsed code block in the review summary comment. This isn't a problem we can fix. GitHub won't allow review comments/suggestions to target lines that are not shown in the PR diff.

**Comment by 2bndy5** [comment]
Its no problem. These short comments are a welcome escape from reality, for now.

**Comment by 2bndy5** [comment]
As I typed that list of caveats, I thought that it might be desirable to have only the PR review's summary comment (with no suggestions shown in the diff). To do that, I would probably support a env var named `CPP_LINTER_PR_REVIEW_NO_SUGGESTION`. That should help reduce PR thread pollution.

**Comment by 2bndy5** [comment]
picture of clang-tidy review comment(s):
![image](https://github.com/cpp-linter/cpp-linter-action/assets/14963867/9d196217-06a5-4d7c-b54e-3b6c54384a46)

**Comment by 2bndy5** [comment]
picture of clang-format review summary comment:
![image](https://github.com/cpp-linter/cpp-linter-action/assets/14963867/d526c71c-88b2-4ae2-ba0b-b10771803ce4)

I didn't include any suggested changes here because they are a bit misleading (although accurate and expected). A more accurate preview of the PR review feature using clang-format would be something like:
![image](https://github.com/cpp-linter/cpp-linter-action/assets/14963867/852dc6be-49cb-47fb-9718-1b767183c33c)

<details><summary>Not this (from same review)</summary>
<p>

![image](https://github.com/cpp-linter/cpp-linter-action/assets/14963867/435a79c5-fe03-4671-9384-ece4cf2ad21e)
![image](https://github.com/cpp-linter/cpp-linter-action/assets/14963867/3a7536cd-4c56-47a4-91c4-782987f7857f)

</p>
</details>

**Comment by 2bndy5** [comment]
Picture of approved review from both tools:
![image](https://github.com/cpp-linter/cpp-linter-action/assets/14963867/d49c3b45-7b8a-400f-b411-1a6434ed805f)
