### ISSUE TITLE
State what python version is used in README

### ISSUE THREAD

**Issue by 2bndy5** [cpp-linter/cpp-linter-action#185]
One thing that would be nice to have in the README is that Python 3.10 needs to be installed in the docker image; that would extend the requirements and make it easier to understand.

_Originally posted by @carlosala in https://github.com/cpp-linter/cpp-linter-action/pull/184#issuecomment-1918963706 (edited for context by 2bndy5)_

**Comment by 2bndy5** [comment]
This information is exclusive to workflows that use docker images not maintained by GitHub. GitHub-maintained docker images (`ubuntu-latest`, `windows-latest`, and `macos-latest`) are already well enough equipped.

**Comment by carlosala** [comment]
Yep, `setup-python` as is set up only creates the structure and the binary is used afterwards, but it needs to have libpython3.11, for example, that should be installed in the system.

**Comment by 2bndy5** [comment]
I just went with 3.11 because 3.12 recently turned  "stable". For now, I have no reason to change that.

I suppose we could switch to whatever version ships with Ubuntu latest LTS release (which I think is currently 3.10).

**Comment by carlosala** [comment]
Yep, latest LTS release is `3.10`.

**Comment by 2bndy5** [comment]
@shenxianpeng Any objections to changing python version to follow Ubuntu latest LTS? It tends to change every couple years in April.

@carlosala would that be preferable?
