### ISSUE TITLE
Incorrectly added `latest` tag for PR testing and not trigger test action

### ISSUE THREAD

**Issue by shenxianpeng** [cpp-linter/cpp-linter-action#212]
I saw the latest commit on the main branch was still adding comments https://github.com/cpp-linter/cpp-linter-action/commit/599f02b992ac2c28d5c83efe4c95959f0f2909cf

Not sure why and how to fix it yet but opening an issue for awareness. maybe the code here needs to be adjusted (haven't looked at it)

https://github.com/cpp-linter/cpp-linter-action/actions/runs/8353366407/workflow#L21-L28

**Comment by 2bndy5** [comment]
```
          git tag --delete latest || true
          git push --delete origin latest || true
```

Maybe the `|| true` is hidding problems that need to be addressed.
