### ISSUE TITLE
Update "What's New" of v2 in README page

### ISSUE THREAD

**Issue by shenxianpeng** [cpp-linter/cpp-linter-action#238]
With many features have been introduced in v2, and #87 can not cover all the features in v2, we may need to update the "What's New" section.

**Comment by 2bndy5** [comment]
Which features are thinking about?

We could generate a CHANGELOG.md file when the docs build is run. But the changes shown in cpp-linter-action releases are not very descriptive about changes in the cpp-linter package.

**Comment by 2bndy5** [comment]
oh ok. Sounds good!
