### ISSUE TITLE
Add 'Used by' section in README.md

### ISSUE THREAD

**Issue by shenxianpeng** [cpp-linter/cpp-linter-action#61]
Since this PR https://github.com/cpp-linter/cpp-linter-action/pull/60 merged, this repo lost all the previous used by links (result is [here](https://github.com/search?p=3&q=shenxianpeng%2Fcpp-linter-action&type=Code)), how about adding 'Used by' section in README.md? we could:

* List the most famous projects like [google/flatbuffers](https://github.com/google/flatbuffers), others display links or number
* Or display like contributor avatars as in many projects

**Comment by 2bndy5** [comment]
In those search results, I'm only seeing the Google/flatbuffers repo worth mentioning. Most of the other projects looked like school projects.

**Comment by shenxianpeng** [comment]
Yes, only google and another one CHIP-SPV/chip-spv. Adding the following badges might encourage more people to use.

[![](https://img.shields.io/badge/google-flatbuffers-brightgreen)](https://github.com/google/flatbuffers)![GitHub Repo stars](https://img.shields.io/github/stars/google/flatbuffers?style=social)
[![](https://img.shields.io/badge/CHIP--SPV-chip--spv-brightgreen)](https://github.com/CHIP-SPV/chip-spv)![GitHub Repo stars](https://img.shields.io/github/stars/CHIP-SPV/chip-spv?style=social)
[![](https://img.shields.io/badge/More%20repositories%20that%20depend%20on-cpp--linter--action-brightgreen)](https://github.com/search?q=shenxianpeng%2Fcpp-linter-action&type=Code)

**Comment by 2bndy5** [comment]
Using badges might confuse people with a status of other projects, but I like the stars count. I also find it a little hard to read the white text on green background.

Maybe something a bit more formal?

## Used By

- [google/flatbuffers](https://github.com/google/flatbuffers) ![GitHub Repo stars](https://img.shields.io/github/stars/google/flatbuffers?style=social)
- [CHIP-SPV/chip-spv](https://github.com/CHIP-SPV/chip-spv) ![GitHub Repo stars](https://img.shields.io/github/stars/CHIP-SPV/chip-spv?style=social)
- [and more](https://github.com/search?q=shenxianpeng%2Fcpp-linter-action&type=Code)

It would be nice if we could have a badge (like the stars count) that shows the total search results.

**Comment by shenxianpeng** [comment]
I like your revision 👍 

Yes, I tried, but I did not find something like this.
> It would be nice if we could have a badge (like the stars count) that shows the total search results.

**Comment by 2bndy5** [comment]
What's happening here? I see [the link](https://github.com/cpp-linter/cpp-linter-action/network/dependents) shows:
![image](https://github.com/cpp-linter/cpp-linter-action/assets/14963867/f6240866-e8c0-47f2-a0cd-55915745c692)
but the badge says 532. Did I misunderstand something?

Otherwise, that is a pretty cool idea! And I like the auto-PR feature.

**Comment by 2bndy5** [comment]
Oh, 465 users of package cpp-linter/cpp-linter-action + 58 users of package shenxianpeng/cpp-linter-action. So, 465 + 58 = 523.

I'm ok with using that badge. You want to open a PR?
