### ISSUE TITLE
`ignore` option's CLI default value includes repo root

### ISSUE THREAD

**Issue by 2bndy5** [cpp-linter/cpp-linter-action#75]
I just noticed another problem when running the action as a python package. If the `--ignore` option is not specified then the default value is `''` which gets translated as the repo root folder `./`. Meaning, no files are linted when `ignore` is not specified to the `cpp-linter` executable script.

I'm opening this to add the issue to my backlog of needed changes.

**Comment by shenxianpeng** [comment]
Wow, a special test case 👍 looks like we also need to add test cases to cover more combinations.

**Comment by 2bndy5** [comment]
Yeah I'm putting together some unit tests that can be run in the CI on future contributions. I've also ran the entire pkg through mypy for type checking; this is also now getting checked in the CI.

I'm currently trying to tackle #74 in a backward compatible way... Sorry I've been a bit distant on this project lately.

**Comment by shenxianpeng** [comment]
I like to have unit test (especially pytest) and mypy for type checking in CI. Enjoy and take your time!
