### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by shenxianpeng** [cpp-linter/cpp-linter-action#80]
- [x] 1. The current logo on cpp-linter-action is different from the logo on Org's home page. I prefer to move the old one.
- [x] ~~2. Add an example snip about how to use cpp-linter as a package with other CI tools, like Jenkins. and which arguments they can not use.~~ Will update the new repo of cpp-linter when it supports on-GitHub-based CI, and this repo is only used for github action.
- [x] ~~3. Replace the second used by with chocolate-doom~~
- [x] 4. Remove old [and more](https://github.com/search?q=shenxianpeng%2Fcpp-linter-action&type=Code) link
- [x] 5. Remove Gitpod badge. it not very necessary and it appears as two lines on the marketplace page https://github.com/marketplace/actions/c-c-lint-action

**Comment by 2bndy5** [comment]
> Add an example snip about how to use cpp-linter as a package with other CI tools, like Jenkins. and which arguments they can not use.

Off the top of my head, I think the args that _can_ be used are
- `ignore`
- `extensions`
- `version`
- `verbosity`
- `database`
- `repo-root`
- `tidy-checks`
- `style`

The only args that _cannot_ be used by non-GitHub-based CI would be anything dealing with the REST API:
- `lines-changed-only`
- `files-changed-only`
- `thread-comments`
- `file-annotations` (which is on by default)

There also might be a few kinks in the process that depend on GitHub env variables, but that might be easier to solve. To port the options in a universal VCS way, we'd have to start using `git` directly (especially for getting the diff), but I'm not sure how well a pull request would be supported with just `git`.

**Comment by 2bndy5** [comment]
It looks like google/flatbuffers stopped using this action: https://github.com/google/flatbuffers/commit/ebbed05137fe15c091d9a5fa50c8a37588596f09 The reason isn't very descriptive, so IDK what prompted them to discontinue.

We should probably remove the google/flatbuffers link in the README's "used by" section.

**Comment by shenxianpeng** [comment]
I also noticed yesterday. Here `https://github.com/google/flatbuffers/pull/7228#issuecomment-1090847180`

**Comment by 2bndy5** [comment]
> > I'm not sure why the cpp linter is failing :/ since there wasn't even a change in the headers for the swift cpp generator
> 
> is this a false positive?

Possibly. I can't view the workflow log, so IDK. My feeling is that the version they were running triggered #82 because they had `lines-changed-only: true`, but had not set `files-changed-only`, but `files-changed-only` is true by default as of #27. I really can't say for sure.
