### ISSUE TITLE
Planned to release cpp-linter-action v2.0.0 (`v2`)

### ISSUE THREAD

**Issue by shenxianpeng** [cpp-linter/cpp-linter-action#87]
- [x] https://github.com/cpp-linter/cpp-linter/issues/1
- [x] Update RREAME.md about what's new
- [x] #91 
- [x] #92 
- [x] #95
- [x] #88
- [x] #98 
- [x] #97

**Comment by shenxianpeng** [comment]
I'm trying to create `main` branch from `master` branch, I noticed the tasks (fixed issues and enhancements) in above description have already been merged into the `master` branch, but we did not release them.

So I think we should release the last `v1` release (v1.5.0) from `master` branch, then create `main` branch for release `v2`.

What are your thoughts? @2bndy5

**Comment by 2bndy5** [comment]
>So I think we should release the last v1 release (v1.5.0) from master branch, then create main branch for release v2.

I was kinda expecting this would happen before resuming review of #83 So I'm ok with releasing v1.5.0 and creating a new main branch.

**Comment by 2bndy5** [comment]
Apparently, showing a warning during install of a python pkg is not a thing you can actually do when using `pip install` (oops).
Instead of adding a warning to the pip output, I can remove all python srcs from master and re-write the setup.py (on master) to redirect installation to the newer package on PyPI.
```py
from setuptools import setup

setup(name="cpp-linter-deprecated", version="0.0.0", install_requires=["cpp-linter"])
```

**Comment by shenxianpeng** [comment]
All the tasks are done, and it's time to release v2.0.0 🚀
