### ISSUE TITLE
Remove publish-pypi.yml (Upload Python Package)

### ISSUE THREAD

**Issue by shenxianpeng** [cpp-linter/cpp-linter-action#91]
> Upload Python Package failed in `v1.5.0` release https://github.com/cpp-linter/cpp-linter-action/runs/8055353233?check_suite_focus=true

Since we have abstract python sources from cpp-linter-action to cpp-linter repo https://github.com/cpp-linter/cpp-linter/issues/1 and publish to PyPI with [cpp-linter](https://github.com/cpp-linter/cpp-linter) repo, since in the next release (v2), the file `.github/workflows/publish-pypi.yml` can be removed.

**Comment by 2bndy5** [comment]
The secret tokens should be removed as well. I think they are now invalid since the release of the cpp-linter pkg (v1.4.6).

**Comment by shenxianpeng** [comment]
OK. I have removed `PYPI_API_TOKEN` and `TEST_PYPI_TOKEN`.
