### ISSUE TITLE
By use of Python package, at action cpp-linter is not found

### ISSUE THREAD

**Issue by ibis-hdl** [cpp-linter/cpp-linter-action#94]
I followed [Running without the docker container](https://github.com/cpp-linter/cpp-linter-action#running-without-the-docker-container) hopefully correct and in my action I have:

```
jobs:
  cpp-linter:
    runs-on: ubuntu-22.04
    steps:
...
    - name: Install conan package manager and cpp-linter
      run: |
        python -m pip install --upgrade pip
        pip --disable-pip-version-check --no-cache-dir install wheel conan \
          git+https://github.com/cpp-linter/cpp-linter-action@v1
...

    - name: Run cpp-linter (clang format && tidy)
      id: linter
      run: |
        cpp-linter --version=14 --style=file --tidy-checks='' --ignore=build --database=build/ci-linux-clang
```

which results to:

```
Run cpp-linter --version=14 --style=file --tidy-checks='' --ignore=build --database=build/ci-linux-clang
  cpp-linter --version=14 --style=file --tidy-checks='' --ignore=build --database=build/ci-linux-clang
  shell: /usr/bin/bash -e {0}
  env:
    CONAN_V2_MODE: 1
/home/runner/work/_temp/405c3607-29ac-42c3-af1e-b4afbe18453f.sh: line 1: cpp-linter: command not found
Error: Process completed with exit code 127.
```

**Comment by 2bndy5** [comment]
The info in setup.py recently moved to pyproject.toml. Was there any warnings or errors when installing the pkg with pip? Can I see the workflow log?

**Comment by 2bndy5** [comment]
https://github.com/cpp-linter/cpp-linter-action/blob/92298bd41cc62a33375a77a515e64bb3daf30fc4/pyproject.toml#L2

I may have to upgrade the `setuptools` requirement to `>=v61`. It would also help to know what version of Python you're using.

The pkg is now [available on PyPI](https://pypi.org/project/cpp-linter/), so you just install it (faster) from there:
```
pip install cpp-linter
```

**Comment by ibis-hdl** [comment]
The cpp-linter related GH action workflow log is here: [3_Install conan package manager and cpp-linter.txt](https://github.com/cpp-linter/cpp-linter-action/files/9463459/3_Install.conan.package.manager.and.cpp-linter.txt)

The python version is
```
-- Found Python3: /usr/bin/python3.10 (found version "3.10.4") found components: Interpreter 
```
what I've got from CMake. I've not seen any other errors. 

Please note, that I'm not familiar with Python's infrastructure, more C++ :) How to install from PyPI? The default location doesn't seem to have these update you mentioned above.

**Comment by 2bndy5** [comment]
In your build logs it does state that it installed a pkg titled `UNKNOWN`:
```
Installing collected packages: UNKNOWN, pluginbase, patch-ng, node-semver, distro, bottle, urllib3, tqdm, python-dateutil, PyJWT, fasteners, conan
Successfully installed PyJWT-2.4.0 UNKNOWN-1 bottle-0.12.23 conan-1.52.0 distro-1.6.0 fasteners-0.17.3 node-semver-0.6.1 patch-ng-1.17.4 pluginbase-1.0.1 python-dateutil-2.8.2 tqdm-4.64.0 urllib3-1.26.12
```
Given that our cpp-linter pkg isn't listed there, I have to assume `UNKNOWN` is our cpp-linter pkg.

When I downgrade my local env version of setuptools to v45, I get a result:
```
pip install git+https://github.com/cpp-linter/cpp-linter-action@v1
...
Installing collected packages: cpp-linter
Successfully installed cpp-linter-1
```
But it shouldn't be named `cpp-linter-1`, and I can still execute `cpp-linter -h` afterwards. So, I think this is still related to https://github.com/cpp-linter/cpp-linter-action/issues/94#issuecomment-1232906182. I just wish I could fully reproduce this "cpp-linter not found" problem.

Either way, installing the pkg from PyPI (`pip install cpp-linter`) should not have this problem because the package on PyPI is already built and doesn't require setuptools to install.

**Comment by ibis-hdl** [comment]
Ok, thanks! I'm using `pip install cpp-linter` for now and it's working as expected. So I'll close the issue.
