### ISSUE TITLE
Rename action from "C/C++ Lint Action" to "C/C++ Linter"

### ISSUE THREAD

**Issue by shenxianpeng** [cpp-linter/cpp-linter-action#97]
I'm wondering whether to change this action's name in the marketplace from "C/C++ Lint Action" to "C/C++ Linter", because the following reasons.

1. To improve the ranking (A good action should be known)
When I search in the marketplace with the keyword "lint", our action is on the first page, but when I search with "linter", the action is on the second page, even though we have a higher start, from the search results, it should be because of not a linter in the name. (see screenshots below)
2. Word "linter" seems used more than "lint" in the marketplace
3. The action name and the organization name use the same suffix - linter

I also want to update the action's description

* From "Automatically checks push & PR changes with clang-format & clang-tidy, then post annotations/comments with faulty results." 
* To "Automatically checks push/pull request changes with clang-format/clang-tidy then post annotations/comments with faulty results." 

Because "&" cannot be displayed in the marketplace. **Or** use the following description from README to make difference with other actions forked from ArtificialAmateur/cpp-linter-action

* "Linting C/C++ code integrating clang-tidy and clang-format to collect feedback provided in the form of thread comments and/or annotations" 

-------------------------------------------------------------------

### screenshots 

Search with "lint", our action is on page 1

![image](https://user-images.githubusercontent.com/3353385/188306230-439cb332-d5f0-4d09-afd8-6aaeb9e69e72.png)

Search with "linter", on page 1, no our action

![image](https://user-images.githubusercontent.com/3353385/188305564-36d508d1-8bec-4f9d-9121-341f4791863b.png)

We are on page 2: https://github.com/marketplace?page=2&q=linter&query=linter&type=actions

![image](https://user-images.githubusercontent.com/3353385/188305721-b177e017-6fb9-4d17-b343-e939053e5814.png)

**Comment by 2bndy5** [comment]
Sounds good to me.

Its a bit weird that github doesn't use the repo's keywords/tags to help prioritize the search. Maybe we have so many that it gets confused?
![image](https://user-images.githubusercontent.com/14963867/188306287-6aece7c9-f146-42a3-9462-278d68144c3c.png)
Maybe the order of keywords has precedence?

**Comment by 2bndy5** [comment]
The ampersand (`&`) is probably because it is an illegal XML character. I'd suggest `/`, but that has special meaning in XML. We should probably replace the `&` with `and`.

**Comment by shenxianpeng** [comment]
> Maybe the order of keywords has precedence?

I have updated the order of keywords. OK, will replace the `&` with `and`
